"""add_saved_filters

Revision ID: 5990bd38093f
Revises: c9d5e7f1a3b4
Create Date: 2026-01-17 02:23:10.399079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5990bd38093f'
down_revision: Union[str, None] = 'c9d5e7f1a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('page', sa.String(length=50), nullable=False),
    sa.Column('filter_json', sa.Text(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_filters_name'), 'saved_filters', ['name'], unique=False)
    op.create_index(op.f('ix_saved_filters_page'), 'saved_filters', ['page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_filters_page'), table_name='saved_filters')
    op.drop_index(op.f('ix_saved_filters_name'), table_name='saved_filters')
    op.drop_table('saved_filters')
    # ### end Alembic commands ###
