"""drop trade_groups tables

Revision ID: ca8253ea5245
Revises: 5990bd38093f
Create Date: 2026-01-17 21:01:59.831031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8253ea5245'
down_revision: Union[str, None] = '5990bd38093f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_group_transactions')
    op.drop_index(op.f('ix_trade_groups_strategy_type'), table_name='trade_groups')
    op.drop_table('trade_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('strategy_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_groups_strategy_type'), 'trade_groups', ['strategy_type'], unique=False)
    op.create_table('trade_group_transactions',
    sa.Column('trade_group_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['trade_group_id'], ['trade_groups.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('trade_group_id', 'transaction_id')
    )
    # ### end Alembic commands ###
